/**
 * @file WipeCertificate.cpp
 * @brief Wipe certificate generation and export implementation
 */

#include "util/WipeCertificate.hpp"

#include "util/JsonEscape.hpp"

#include <algorithm>
#include <format>
#include <fstream>

namespace util {

namespace {

constexpr uint64_t KIB = 1'024;
constexpr uint64_t MIB = KIB * 1'024;
constexpr uint64_t GIB = MIB * 1'024;

auto format_size(uint64_t bytes) -> std::string {
    if (bytes >= GIB) {
        return std::format("{:.1f} GB", static_cast<double>(bytes) / static_cast<double>(GIB));
    }
    if (bytes >= MIB) {
        return std::format("{:.1f} MB", static_cast<double>(bytes) / static_cast<double>(MIB));
    }
    if (bytes >= KIB) {
        return std::format("{:.1f} KB", static_cast<double>(bytes) / static_cast<double>(KIB));
    }
    return std::format("{} bytes", bytes);
}

auto format_speed(uint64_t bytes_per_sec) -> std::string {
    if (bytes_per_sec == 0) {
        return "not measured";
    }
    return std::format("{:.1f} MB/s",
                       static_cast<double>(bytes_per_sec) / static_cast<double>(MIB));
}

auto format_duration(uint64_t seconds) -> std::string {
    const auto hours = seconds / 3'600;
    const auto minutes = (seconds % 3'600) / 60;
    const auto secs = seconds % 60;
    if (hours > 0) {
        return std::format("{}h {:02d}m {:02d}s", hours, minutes, secs);
    }
    if (minutes > 0) {
        return std::format("{}m {:02d}s", minutes, secs);
    }
    return std::format("{}s", secs);
}

auto verification_label(const WipeCertificateData& data) -> std::string {
    if (!data.verification_enabled) {
        return "not requested";
    }
    return data.verification_passed ? "passed" : "FAILED";
}

auto device_basename(std::string_view path) -> std::string {
    const auto pos = path.rfind('/');
    auto name = std::string{pos == std::string_view::npos ? path : path.substr(pos + 1)};
    // Keep file names shell- and glob-friendly
    std::ranges::replace(name, '/', '_');
    return name;
}

}  // namespace

auto iso8601_utc(std::chrono::system_clock::time_point time) -> std::string {
    return std::format("{:%Y-%m-%dT%H:%M:%SZ}", std::chrono::floor<std::chrono::seconds>(time));
}

auto certificate_timestamp(std::chrono::system_clock::time_point time) -> std::string {
    return std::format("{:%Y%m%d-%H%M%S}", std::chrono::floor<std::chrono::seconds>(time));
}

auto wipe_certificate_json(const WipeCertificateData& data) -> std::string {
    std::string json;
    json += "{\n";
    json += "  \"type\": \"storage-wiper-certificate\",\n";
    json += std::format("  \"tool_version\": \"{}\",\n", json_escape(data.tool_version));
    json += std::format("  \"success\": {},\n", data.success ? "true" : "false");
    json += "  \"device\": {\n";
    json += std::format("    \"path\": \"{}\",\n", json_escape(data.device_path));
    json += std::format("    \"model\": \"{}\",\n", json_escape(data.model));
    json += std::format("    \"serial\": \"{}\",\n", json_escape(data.serial));
    json += std::format("    \"size_bytes\": {},\n", data.size_bytes);
    json += std::format("    \"is_partition\": {},\n", data.is_partition ? "true" : "false");
    json += std::format("    \"parent_disk\": \"{}\"\n", json_escape(data.parent_disk));
    json += "  },\n";
    json += "  \"wipe\": {\n";
    json += std::format("    \"algorithm\": \"{}\",\n", json_escape(data.algorithm_name));
    json += std::format("    \"nist_category\": \"{}\",\n", json_escape(data.nist_category));
    json += std::format("    \"passes\": {},\n", data.total_passes);
    json += std::format("    \"started_at\": \"{}\",\n", json_escape(data.started_at));
    json += std::format("    \"completed_at\": \"{}\",\n", json_escape(data.completed_at));
    json += std::format("    \"duration_seconds\": {},\n", data.duration_seconds);
    json += std::format("    \"peak_speed_bytes_per_sec\": {},\n", data.peak_speed_bytes_per_sec);
    json += std::format("    \"bad_block_count\": {}\n", data.bad_block_count);
    json += "  },\n";
    json += "  \"verification\": {\n";
    json += std::format("    \"enabled\": {},\n", data.verification_enabled ? "true" : "false");
    json += std::format("    \"passed\": {}\n", data.verification_passed ? "true" : "false");
    json += "  }\n";
    json += "}\n";
    return json;
}

auto wipe_certificate_text(const WipeCertificateData& data) -> std::string {
    const std::string rule(64, '=');
    const std::string thin(64, '-');

    std::string text;
    text += rule + "\n";
    text += "WIPE CERTIFICATE\n";
    text += std::format("Generated by Storage Wiper {}\n", data.tool_version);
    text += rule + "\n";
    text += std::format("Status:               {}\n", data.success ? "SUCCESS" : "FAILED");
    text += std::format("Device:               {}\n", data.device_path);
    text += std::format("Scope:                {}\n",
                        data.is_partition ? "partition of " + data.parent_disk : "whole disk");
    text += std::format("Model:                {}\n", data.model.empty() ? "Unknown" : data.model);
    text +=
        std::format("Serial:               {}\n", data.serial.empty() ? "Unknown" : data.serial);
    text += std::format("Size:                 {} ({} bytes)\n", format_size(data.size_bytes),
                        data.size_bytes);
    text += std::format("Algorithm:            {}\n", data.algorithm_name);
    text += std::format("Sanitization:         {}\n", data.nist_category);
    text += std::format("Passes:               {}\n", data.total_passes);
    text += std::format("Started (UTC):        {}\n", data.started_at);
    text += std::format("Completed (UTC):      {}\n", data.completed_at);
    text += std::format("Duration:             {}\n", format_duration(data.duration_seconds));
    text += std::format("Peak speed:           {}\n", format_speed(data.peak_speed_bytes_per_sec));
    text += std::format("Verification:         {}\n", verification_label(data));
    if (data.bad_block_count > 0) {
        text += std::format("Bad sectors:          {} could not be overwritten\n",
                            data.bad_block_count);
    }
    text += thin + "\n";
    text += "This certificate records a sanitization operation performed by Storage\n";
    text += "Wiper at the time shown above. Overwrite algorithms correspond to the\n";
    text += "NIST SP 800-88 \"Clear\" category; firmware erase corresponds to \"Purge\".\n";
    return text;
}

auto wipe_certificate_default_dir() -> std::filesystem::path {
    namespace fs = std::filesystem;

    if (const char* xdg = std::getenv("XDG_DATA_HOME"); xdg != nullptr && *xdg != '\0') {
        return fs::path{xdg} / "storage-wiper" / "certificates";
    }
    if (const char* home = std::getenv("HOME"); home != nullptr && *home != '\0') {
        return fs::path{home} / ".local" / "share" / "storage-wiper" / "certificates";
    }
    return {};
}

auto write_certificate_to_base(const std::filesystem::path& base, const WipeCertificateData& data)
    -> std::expected<std::filesystem::path, std::string> {
    namespace fs = std::filesystem;

    std::error_code ec;
    if (base.has_parent_path()) {
        fs::create_directories(base.parent_path(), ec);
        if (ec) {
            return std::unexpected(
                std::format("cannot create {}: {}", base.parent_path().string(), ec.message()));
        }
    }

    const auto json_path = base.string() + ".json";
    {
        std::ofstream file{json_path, std::ios::trunc};
        if (!file) {
            return std::unexpected("cannot write " + json_path);
        }
        file << wipe_certificate_json(data);
        if (!file) {
            return std::unexpected("failed to write " + json_path);
        }
    }

    const auto text_path = base.string() + ".txt";
    {
        std::ofstream file{text_path, std::ios::trunc};
        if (!file) {
            return std::unexpected("cannot write " + text_path);
        }
        file << wipe_certificate_text(data);
        if (!file) {
            return std::unexpected("failed to write " + text_path);
        }
    }

    return base;
}

auto write_wipe_certificate(const std::filesystem::path& directory, const WipeCertificateData& data)
    -> std::expected<std::filesystem::path, std::string> {
    namespace fs = std::filesystem;

    std::error_code ec;
    fs::create_directories(directory, ec);
    if (ec) {
        return std::unexpected(
            std::format("cannot create {}: {}", directory.string(), ec.message()));
    }

    const auto base =
        directory / std::format("wipe-{}-{}",
                                certificate_timestamp(std::chrono::system_clock::now()),
                                device_basename(data.device_path));
    return write_certificate_to_base(base, data);
}

}  // namespace util
